name: flutter_stage_status_picker
description: "A Flutter widget that provides a dropdown for selecting statuses with customizable options."
version: 1.0.0
homepage: https://github.com/DarienRomero/flutter_stage_status_picker

environment:
  sdk: ^3.5.3
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  diacritic: ^0.1.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
